### ISSUE TITLE
email validator is overzealous

### ISSUE THREAD

**Issue by zuzak** [UKHomeOfficeForms/hof-form-controller#26]
The default email validator is problematic. Here's a railroad diagram of the current functionality:
![image](https://user-images.githubusercontent.com/817054/70630122-f306db00-1c22-11ea-97f5-d6acc8067d73.png)

This doesn't accept email addresses with apostrophes in them, which is something which is not uncommon (e.g. Dermot.O'Leary@example.com). Additionally, it doesn't accept about a third of the new [ICANN top-level domains](https://www.icann.org/resources/pages/tlds-2012-02-25-en), which are six characters or longer. As these new domains get popular, more and more email addresses will be in use, making this incorrect validation more of an issue.

The [GOV.UK Design System](https://design-system.service.gov.uk/patterns/email-addresses/) has no specific advice on email validation regex. Suggestions on cross-government Slack about this problem include:
* adding a check for MX DNS records, and accepting anything in the username portion of the URL (in NodeJS, the [legit](https://github.com/martyndavies/legit) library would work fine)
* just validating for an `@` symbol and the presence of a `.` in the hostname portion

**Comment by sulthan-ahmed** [comment]
Makes sense, go for it @zuzak
